### ISSUE TITLE
[FEATURE REQUEST] Online Appointment Scheduling

### ISSUE THREAD

**Issue by DmytroLitvinov** [schedule-x/schedule-x#131]
Hi there,
Thank you for your product.

**Describe the solution you'd like**
A similar solution to calendly.

**Comment by tomosterlund** [comment]
Hi @DmytroLitvinov. First of all, thanks for the appreciation!

By online appointment scheduling, do you mean like a full fledged website with a backend to save events? If yes, this is not planned at the moment, though it is one of the options I'm considering as a follow-up project to the open source version. I'll mark this issue as closed for now, since this is not something that is on the table for now. But thanks again for your interest.

**Comment by DmytroLitvinov** [comment]
@tomosterlund , no, I meant UI and JS logic where we provide with JSON for example list of events which are available to book and then there is logic on frontend.

**Comment by tomosterlund** [comment]
Hi. I see. If I understand you correctly, you mean that you wish for a way to initialize your own calendar, and fill it with events based on a list of events that you have in some data structure.

This is already possible: https://schedule-x.dev/docs/calendar

**Comment by DmytroLitvinov** [comment]
I meant booking of events for customers like Calendly provides something like that. Here is an example what I mean: https://calendly.com/renovatehub/schedule-x-demo-page?month=2024-01
