### ISSUE TITLE
Update date field when clicking a day in month view

### ISSUE THREAD

**Issue by sn0n** [schedule-x/schedule-x#133]
** The bug**

Updating the date entry in top right when clicking a day in month view. This will allow viewing that day directly when switching to day view. 

**To Reproduce**

1. Go to month view
2. Click on a day
3. Select day view from views menu
4. It goes to the day that was already typed in day view, not the currently selected day in month view. 

**Expected behavior**

Should go to a selected day in month view when selecting day view.

**Comment by tomosterlund** [comment]
Hi @sn0n. Thanks for opening this issue!

I like this. This would also be an alignment with the way the Google Calendar works. I'll go ahead and mark this as an enhancement though, instead of a bug, since this was not yet considered a feature of Schedule-X. Will keep you posted when this feature becomes available.

**Comment by tomosterlund** [comment]
Hey there @sn0n 

I settled on a slightly different approach. I figured, not everyone will have the day view installed, so it's better to let you implementers decide what happens when clicking a date.

For this I added the calendar-controls plugin: https://schedule-x.dev/docs/calendar/plugins/calendar-controls

You could combine this with using the `onClickDate` callback, to achieve what you described.

Let me know if you need any help implementing this.
