### ISSUE TITLE
feature: add and edit events

### ISSUE THREAD

**Issue by kankanai** [schedule-x/schedule-x#142]
I have already used it. Currently, it is used for display, but there is no new function. If it is supported, it would be great, such as right clicking on the interface to create or edit an existing schedule

**Comment by kankanai** [comment]
such as https://github.com/nhn/tui.calendar

**Comment by tomosterlund** [comment]
Hi there, thanks for opening this issue!

I definitely plan to build this down the road. For now, you can use the callbacks `onEventClick` `onClickDate` and `onClickDateTime` to achieve a similar thing as in the example you sent. You then of course need to implement the form yourself.

The callbacks are documented here: https://schedule-x.dev/docs/calendar/configuration

**Comment by Artenio** [comment]
Event management is adeptly handled in the current system. However, the integration of a universal "event editor form" poses challenges due to varying use-cases. Each event might require differing levels of detail depending on its specific context. In light of this, customizing forms to suit individual use-cases might be more practical than attempting a one-size-fits-all solution.

The maybe-correct approach involves manually creating your own form and handling the form submission to facilitate new event creation. This means designing a custom form tailored to your specific use-case and then managing the submission process, which interacts with the [Schedule-X Calendar Events](https://schedule-x.dev/docs/calendar/events) functionalities.

Alternatively, if there's a preference to incorporate these features directly within the calendar, bypassing external elements, new handlers can be created. These would include callbacks like onEventClick, onClickDate, and onClickDateTime, as suggested by @tomosterlund.

**Comment by m0tay** [comment]
@tomosterlund do the callbacks fire when on mobile? I've tried on chrome devtools, and it seem to not fire. Am I doing somehting wrong?

**Comment by tomosterlund** [comment]
@aonghas and @m0tay thanks for reporting your issues. That is in general very helpful. However, please create separate issues when it doesn't directly relate to the exact issue of the OP.

@kankanai regarding this feature request: I've decided to build this feature as a first feature of the premium offering of Schedule-X, meaning I won't build it here in the open sourced repo. Thanks for taking the time to suggest the feature though
