### ISSUE TITLE
Feature request: "Today" and "forward backward" controls set in config

### ISSUE THREAD

**Issue by segheysens** [schedule-x/schedule-x#316]
**Is your feature request related to a problem? Please describe.**  
I can try to make a commit at some point, but it would be awesome if the "today" button and "forward backward" controls could resize on every screen size, and their visibility could be controlled in the configuration object. I have a screen in my app that is primarily in the "day" view, so it would be nice to have the "forward backward" and "Today" visible.

**Describe the solution you'd like**  
I would like to be able to pass this as a config parameters like this:
```
const config = [ todayButtonVisible: true, forwardBackwardVisible: true ]
```

**Additional context**  
When on small screens or in skinny parent containers, the "Today" button and forward/backward navigation buttons are hidden, but I'd like for these to be shown with the right config values

<img width="329" alt="image" src="https://github.com/schedule-x/schedule-x/assets/3592134/ae946415-e9d5-4f72-ab22-4bae06ba2341">

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by tomosterlund** [comment]
I think maybe the better option here would be a simple CSS override

**Comment by tomosterlund** [comment]
I think maybe the better option here would be a CSS override on your end. My main concern when hiding those buttons was that I find it optically more appealing with a 1-row header than 2 rows. But if you really need the functionality of course that could be made possible. To enable achieving this through a CSS override, we would need to hide `ForwardBackwardNavigation` by means of CSS instead of JS, in `packages/calendar/src/components/header/calendar-header.tsx`. The Today button already does this.

Then you could write:

```css
.sx__calendar-header {
  flex-wrap: wrap;
}

.sx__is-calendar-small .sx__today-button {
  display: initial;
}
```

And then the same with the forward/backward navigation.

Any thoughts?

**Comment by segheysens** [comment]
Yeah, that would work fine for me 👍 would definitely appreciate the consistency in using CSS for styling.
