### ISSUE TITLE
iCalendar url source support

### ISSUE THREAD

**Issue by justin-hackin** [schedule-x/schedule-x#371]
**Is your feature request related to a problem? Please describe.**  

A plugin that allows the calendar's events to be populated by an iCalendar URL much like the [fullcalendar plugin](https://fullcalendar.io/docs/icalendar).

**Describe the solution you'd like**  

This plugin should:
* Use code this is similar to [fullcalendar plugin](https://github.com/fullcalendar/fullcalendar/blob/main/packages/icalendar/src/event-source-def.ts) to fetch ics data, parse into objects, and expand recurring events. 
* Populate `$app.calendarEvents.list` with events.
* Give the user a mechanism that enables manually refreshing the event stream within react components

Some design decisions:
* should the range of recurrence be fixed to the view time bounds (month, day, week) and the calendar data be re-expanded upon every view change? Or is it best to expand generously and only refetch data from explicit user calls?
* will it need to expand the recurrence on its own or can it make use of the recurrence plugin? if the latter, is there a way to expand the supported rules for a read-only mode? Or, is it acceptable for this plugin to ignore the unsupported rules from the recurrence plugin?
* is there a way to enforce that no interactivity plugins are active when this plugin is active? 
* where should the ics calendar URL be provided? should events value for config be like fullcalendar `{ url: 'https://mywebsite/icalendar-feed.ics', format: 'ics' }`

**Additional context**  

[Starting discussion on discord](https://discord.com/channels/1183076861509632011/1193105586800308224/1230662427666944090)

**Things that could speed up the process**
- [ x ] I can picture implementing at least parts of this feature
- [  ] I believe I know how to do this, and am willing to implement the whole thing.

I might be able to do this but I want to be more sure about the scope. I have only looked at the plugin interface and don't know the codebase yet.

**Comment by tomosterlund** [comment]
Thank you for a great issue! I'm all for this.

Some thoughts of mine to your considerations:

**- should the range of recurrence be fixed to the view time bounds (month, day, week) and the calendar data be re-expanded upon every view change? Or is it best to expand generously and only refetch data from explicit user calls?**

I would say: we could play around a little with the time it takes to add all events upon parsing, compared to just a smaller number of them. If we're talking a small number of ms for adding the already parsed events, I don't mind an eager loading. If we're talking hundreds of ms for a few hundred events, maybe adding them lazily is better.

**- will it need to expand the recurrence on its own or can it make use of the recurrence plugin? if the latter, is there a way to expand the supported rules for a read-only mode? Or, is it acceptable for this plugin to ignore the unsupported rules from the recurrence plugin?**

If you want an almost full-support, I would say we use: https://github.com/jkbrzt/rrule

If a quick-fix is preferred, then we can use the already existing plugin of this library.

I lean towards the former, since I think it has the potential to get messy if we start mixing the interactivity-supporting recurrence plugin with non-interactive rules.

**- is there a way to enforce that no interactivity plugins are active when this plugin is active?**

This is the default behavior :) 

**- where should the ics calendar URL be provided? should events value for config be like fullcalendar { url: 'https://mywebsite/icalendar-feed.ics', format: 'ics' }**

Maybe like this?

```
const calendar = createCalendar({
  // ... other config
  plugins: [
    createIcalPlugin({
      url: 'https://mywebsite/icalendar-feed.ics', format: 'ics'
    })
  ]
})
```
```

**Comment by justin-hackin** [comment]
> Thank you for a great issue! I'm all for this.
> 
> Some thoughts of mine to your considerations:
> 
> **- should the range of recurrence be fixed to the view time bounds (month, day, week) and the calendar data be re-expanded upon every view change? Or is it best to expand generously and only refetch data from explicit user calls?**
> 
> I would say: we could play around a little with the time it takes to add all events upon parsing, compared to just a smaller number of them. If we're talking a small number of ms for adding the already parsed events, I don't mind an eager loading. If we're talking hundreds of ms for a few hundred events, maybe adding them lazily is better.
> 

Sounds sensible 👍

> **- will it need to expand the recurrence on its own or can it make use of the recurrence plugin? if the latter, is there a way to expand the supported rules for a read-only mode? Or, is it acceptable for this plugin to ignore the unsupported rules from the recurrence plugin?**
> 
> If you want an almost full-support, I would say we use: https://github.com/jkbrzt/rrule
> 

The code I linked to uses ical.js which uses rrule library for expansion.

> If a quick-fix is preferred, then we can use the already existing plugin of this library.
> 
> I lean towards the former, since I think it has the potential to get messy if we start mixing the interactivity-supporting recurrence plugin with non-interactive rules.
> 

I'm inclined to agree considering this.

> **- is there a way to enforce that no interactivity plugins are active when this plugin is active?**
> 
> This is the default behavior :)

Great 👍

> 
> **- where should the ics calendar URL be provided? should events value for config be like fullcalendar { url: 'https://mywebsite/icalendar-feed.ics', format: 'ics' }**
> 
> Maybe like this?
> 
> ```
> const calendar = createCalendar({
>   // ... other config
>   plugins: [
>     createIcalPlugin({
>       url: 'https://mywebsite/icalendar-feed.ics', format: 'ics'
>     })
>   ]
> })
> ```

Yeah, that was the other approach I thought of but I noticed that the recurrence plugin augmented the entries in the events array. This made me wonder about the typing of the options but I haven't looked into if/how a plugin augments the options TS types. 

I have more pressing matters for my project in the short term but I hope I can make such a contribution. I'm going to circle back on this and report capacity next week.

**Comment by justin-hackin** [comment]
The problem with this feature is that requesting ics data from other domains will result in CORS errors. I discovered this when I started using other-domained ics URLs with fullcalendar, [known "bug"](https://github.com/fullcalendar/fullcalendar/issues/7476). Perhaps it's better to enable an ics string as input instead. This will be more extensible e.g. in the case where you want authenticated requests via google calendar api.

**Comment by justin-hackin** [comment]
It's easy to work around the CORS limitation if needed by making the ics requests on the backend. Remix made this pretty easy to do. Not all urls will be CORS protected so there's still value in allowing urls. Most of the work is in parsing the ics text anyway.

**Comment by tomosterlund** [comment]
> It's easy to work around the CORS limitation if needed by making the ics requests on the backend and exposing to your own api endpoint that returns ics. Remix made this pretty easy to do. Not all urls will be CORS protected so there's still value in allowing urls. Most of the work is in parsing the ics text anyway.

Probably there could be value in providing both options: either to just add a string for parsing, or fetching the data per URL. The API itself is probably the smaller part of the work here though :)

**Comment by tomosterlund** [comment]
> I have more pressing matters for my project in the short term but I hope I can make such a contribution. I'm going to circle back on this and report capacity next week.

Let me know if you want to have a chat at some point on this. I'd be glad to help out if you'd like to build this
