### ISSUE TITLE
Callback event function for Today button

### ISSUE THREAD

**Issue by KOVex13** [schedule-x/schedule-x#375]
Is it possible to add a separate function to the Today button event, similar to onClickDate(date)? Or call this function instead of onRangeUpdate(range)

**Comment by tomosterlund** [comment]
Can you help me understand your use case for this?

My assumption was that `onRangeUpdate` would cover this.

One scenario would be:
1) user is somewhere in a month in a future
2) user clicks "Today"
3) `onRangeUpdate` is called
4) you handle this by checking if you need to load more events

The other that I see:
1) User views today's date in the current view
2) User clicks "Today"
3) nothing happens

If there was an `onClickToday` callback, what would you use it for?

**Comment by KOVex13** [comment]
Application option.
1. To change the date in the external DatePicker.
2. Display the selected date outside the calendar module
3. Obtaining data for a specific number.
The onClickDate(date) function is quite suitable for these purposes, but it does not work when the “today” button is clicked.

**Comment by tomosterlund** [comment]
Got it 👍 

You can then achieve the same result as the proposed api by adding an event listener for clicks on `.sx__today-button`. Since this is a very rare use case I think that will be the better option, compared to implementing this as part of the library. My rationale for this is that the today button is part of the library core, which I'm doing my best to keep as compact and performant as possible 

Thanks anyway for suggesting this feature, and don't hesitate to share any further ideas :)
