### ISSUE TITLE
eventsServicePlugin is uninitialized in react

### ISSUE THREAD

**Issue by justin-hackin** [schedule-x/schedule-x#407]
While I was working on a plugin-free POC of how to do expanding ICS strings with the library for [this feature](https://github.com/schedule-x/schedule-x/issues/371), I managed use `icalendar-expander` to generate the events but when I try to use eventsServicePlugin.set inside the useEffect for it, I find that the plugin `init` function was not called because `this.eventsFacade` is undefined. 

**Reproduction:**

https://stackblitz.com/edit/remix-run-remix-c7krb4?file=app%2Froutes%2F_index.tsx

I tried looking into the root cause of this but I'm getting pretty tired. Maybe it's not intended to be used with react. I will have to learn more about the plugin system as I come to write one so perhaps I will understand better then.

**Comment by tomosterlund** [comment]
Hi. I see 2 things:

1. The `eventsFacade` or `calendarApp.events` will be deprecated with v2. I forgot to add this to the v2-list though. Thanks! Did you see this documented anywhere, because if that's the case I need to delete it. Though the eventsFacade still works, https://schedule-x.dev/docs/calendar/plugins/events-service is the new official way.
2. Whether using the new plugin, or the `eventsFacade`, you can't use this before the calendar has been initialized, which is the case in that dependency-free `useEffect`-hook; it runs before the calendar had a chance to initialize the plugin

I forked and updated the Stackblitz example a little: https://stackblitz.com/edit/remix-run-remix-te8jfl?file=app%2Froutes%2F_index.tsx

**Comment by justin-hackin** [comment]
> Hi. I see 2 things:
> 
>     1. The `eventsFacade` or `calendarApp.events` will be deprecated with v2. I forgot to add this to the v2-list though. Thanks! Did you see this documented anywhere? Because if that's the case I need to delete it 😬 Though the eventsFacade still works, https://schedule-x.dev/docs/calendar/plugins/events-service is the new official way.
> 
>     2. Whether using the new plugin, or the `eventsFacade`, you can't use this before the calendar has been initialized, which is the case in that dependency-free `useEffect`-hook; it runs before the calendar had a chance to initialize the plugin
> 
> 
> I forked and updated the Stackblitz example a little: https://stackblitz.com/edit/remix-run-remix-te8jfl?file=app%2Froutes%2F_index.tsx

No I didn't see anything about `eventsFacade` in the docs, I just discovered it on the plugin because of the runtime error. The example doesn't address the problem I'm trying to solve: initializing the calendar with the plugin. Is there anything that can be observed on the calendar instance for this?

**Comment by tomosterlund** [comment]
Now I think I managed to connect the dots: what you're trying to achieve is to set the array of events in order to expand recurring events, and parse ical events?

In that case you probably shouldn't use the events service plugin. My recommendation would be:

have a look at how the event-recurrence plugin is built. There is an `init` method in the plugin, which is invoked by the calendar itself, and then the internal list of events is updated with the recurring events, through `$app.calendarEvents.list.value`. That would be my approach for building an ical plugin as well

**Comment by tomosterlund** [comment]
If you want to I could start a branch with some basic functions and boilerplate of how I would try to build that ical functionality, and then you could continue building on top of that?
