### ISSUE TITLE
Toggling Date Picker bug

### ISSUE THREAD

**Issue by statushub-bartek** [schedule-x/schedule-x#440]
**Context:**

- Latest versions of Chrome, Firefox and Safari
- schedule-x v1.42.0

**Describe the bug**

There is an inconsistency regarding Date Picker toggling - it can't be opened by clicking directly on chevron icon and it can't be closed by clicking inside the date field.

**To Reproduce**

1. Click Date Picker chevron icon > Date Picker dropdown is not being opened
2. Click Date Picker date > Date Picker dropdown opens up > click Date Picker date again > Date Picker dropdown is not being closed

**Expected behavior**
For accessibility reasons expected behavior is to open and close Date Picker dropdown by clicking anywhere inside the date field.

**Comment by tomosterlund** [comment]
Thanks for opening this issue!

I'll go ahead and mark it as a bug due to the missing behavior when clicking the chevron arrow: this is a bug.

Regarding not closing on clicking the field: that's the wanted behavior so far. If you take a look at the behavior of the default date pickers in Chrome and Safari, they also don't close. The one in Firefox does however. But most importantly, why do you find it more _accessible_ with closing on clicks outside?

**Comment by statushub-bartek** [comment]
You're right, staying consistent with Chrome/Safari default date picker behavior is fine.
