### ISSUE TITLE
$app undefined

### ISSUE THREAD

**Issue by mikeabbott10** [schedule-x/schedule-x#454]
When I try to use the RecurrencePlugin an error comes up in console saying “Error: Plugin not yet initialized” from `@schedule-x_event-recurrence.js:956` .
It means that $app is null or undefined. I call `recurrencePlugin = createEventRecurrencePlugin()` inside the setup() method of my component and call `this.recurrencePlugin.eventsFacade.set([...])` inside the mounted() method (the set method is the one which triggers the error).
I don't understand what I am supposed to do. The imports all look correct: `import {createEventRecurrencePlugin} from “@schedule-x/event-recurrence”; , import {createCalendar, viewMonthAgenda, viewMonthGrid} from “@schedule-x/calendar”;`...

Same error happens if I try to use createCalendarControlsPlugin, again, because $app is undefined.

Vue version: 3.4.19

**Comment by tomosterlund** [comment]
Hie @mikeabbott10, this reminds me I need to improve the error messages of the plugins.

If you get this error, it just means the calendar hasn't been fully initialized yet, and you can't access the internal app context. The events service plugin is also not designed for the initial configuration of events, but merely to edit them once it's up and running. I probably need to clarify this in the docs. I think what you want to do is:

```
const calendarApp = createCalendar({
  // .. other config
  events: [/** your events */],
})
```

Let's keep this issue open though, since I should really improve the error messages and docs on this.

**Comment by mikeabbott10** [comment]
Hi Tom!
Yes, that is the way I'm using it right now, but it would be great if I could use the plugins as well. 
I don't experience any problem using `createEventModalPlugin`, but the same thing doesn't apply to the two I mentioned above :(

**Comment by tomosterlund** [comment]
_You can use them though_, and $app will be defined, once the plugins have been initialized.

But if you try to invoke methods on the plugins before they have been initialized, like during mounted, it won't work.

An example:

❌ will fail:
```vue
onMounted(() => {
  calendarControls.setView('day')
})
```

✅ will work
```vue
<template>
  <div>
    <ScheduleXCalendar :calendar-app="calendarApp" />
    <button @click="calendarControls.setView('monthGridView.name')">Set other view</button>
  </div>
</template>
```

**Comment by tomosterlund** [comment]
Tried to improve the error messages on this, also by linking to the relevant documentation, in v1.44.0

Thanks for opening this issue!
