### ISSUE TITLE
Invalid event when using slot monthGridEvent at callback onEventClick

### ISSUE THREAD

**Issue by KOVex13** [schedule-x/schedule-x#469]
Very interesting behavior of the onEventClick(calendarEvent) callback function.
I use Vue3 slot #monthGridEvent="{ calendarEvent }"
And when you click on the event for the first time, another event is passed to the function (apparently the next one from the array), when you click again, everything is fine. When you click on another event, the behavior is the same. Those. always gives the wrong event on the first click.
I remove the use of the custom slot, everything is fine.
In turn, the #monthAgendaEvent="{ calendarEvent }" Slot works fine.

**Comment by KOVex13** [comment]
Addition. This behavior is reproduced in FireFox.
In Chrome, the first click does not trigger a callback.

**Comment by tomosterlund** [comment]
thanks for reporting this

It’s interesting. I couldn’t reproduce this exact behavior, but on my end the first click doesn’t invoke any callback, and on the second click the callback is called with the correct event.

Will have to look into this a bit more in detail. Currently I’m not certain if the problem is in the library core, or in my usage of the Vue Teleport API

**Comment by tomosterlund** [comment]
I introduced this bug in `@schedule-x/vue@1.40.0`.

I'll get started on fixing it now, but not sure if I'll manage a release today. If you need it fixed right away I suggest you roll back to 1.39.0 until this fix is finished
