### ISSUE TITLE
Add "all day" label to day and week views events

### ISSUE THREAD

**Issue by statushub-bartek** [schedule-x/schedule-x#578]
It would be nice to explicitly mark all day events in day and week views with a label and separate them visually from the rest of events. 

There's an example of how Apple does that in their calendar (right side):
![4rVmrrlQ](https://github.com/user-attachments/assets/83f9546e-ce7b-4c39-b84a-750697212913)

**Comment by tomosterlund** [comment]
Now that you say it, I see why this could maybe confuse someone when looking at the calendar at first. Especially if the person is not used to Google calendar.

I'll have a look at how I might make this a bit clearer, though I'll probably try if I can achieve this with visual cues rather than a label
