### ISSUE TITLE
Have an event run over several days without it being in the headers (online)

### ISSUE THREAD

**Issue by ThomasSvgt** [schedule-x/schedule-x#669]
Hello,
I'm using the module, and I'm stuck on one point.
I have events that take place over several days, and they are displayed correctly, but at the top of the calendar.
However, I need the display to be like a normal event, except that it continues on the other days. 
I can't create alternative events to fill the gap, as this would mean processing 300 events X 2 or X 3, for example.
Could you suggest a simple solution?
Thank you very much.
Have a nice day!

**Comment by tomosterlund** [comment]
Hi there,

Thanks for opening this feature request.

This is not possible right now by any other means than the one you already mentioned: processing the events and splitting them up in different days. I also don't think I will enable this behavior by configuration, because I fear that the complexity added to the project might cost more than the value it brings.

I believe most users are used to multi-day events being displayed in a date grid like in Schedule-X, since this has kind of been standardized in Google calendar and Outlook.

Hope you can find a solution that works for your users anyway!

**Comment by ThomasSvgt** [comment]
Hello,
Thank you for your response. I understand and I will try to create some object by the back.
See you
