### ISSUE TITLE
Is it possible (for us) to add a playhead to the resource view and tick through it in real time?

### ISSUE THREAD

**Issue by rsslldnphy** [schedule-x/schedule-x#776]
We're considering buying a premium licence for the resource view, however our use case is to show it in real time with a playhead ticking along it as time passes (see mockup in screenshot), with the timeline scrolling along with it, and scheduled events, which may have their start or end times updated, growing or shrinking as they do. I feel like this is _likely_ possible to some extent (though I'm not sure how hard it would be for us to add the playhead), but it's hard to tell without being able to try it out. Do you have an idea of how possible/easy this might be?

![image](https://github.com/user-attachments/assets/fb337f8a-9baa-4a41-9d0c-4484e37ba62c)

(Apologies haven't used the issue template bc this is more a question than a feature request or bug)

**Comment by tomosterlund** [comment]
I would gladly add this to the library myself, and bump it towards the top of my prio-list.

Since I'm kind of swamped with requests right now though, I'd only prioritize once you have the license.

If you have any other questions about premium, I'm also available for a chat here: https://calendly.com/schedule-x/lets-chat
